// <auto-generated />
using System;
using FR.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FR.Infrastructure.Migrations
{
    [DbContext(typeof(TournamentDbContenxt))]
    [Migration("20190918175659_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("FR.Domain.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LeagueTitle");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("FR.Domain.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AwayTeam");

                    b.Property<int>("AwayTeamGoals");

                    b.Property<int?>("GroupId");

                    b.Property<string>("HomeTeam");

                    b.Property<int>("HomeTeamGoals");

                    b.Property<DateTime>("KickoffAt");

                    b.Property<string>("LeagueTitle");

                    b.Property<int>("Matchday");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("FR.Domain.Models.Result", b =>
                {
                    b.HasOne("FR.Domain.Models.Group", "Group")
                        .WithMany("Results")
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
